name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Docker image
      run: | 
        echo "${{secrets.DOCKERPW}}" | docker login -u "devashish07" --password-stdin
        docker build -t devashish07/flask-app-hello-world:v1 .
        docker push devashish07/flask-app-hello-world:v1

        
